(deftheme iomonad
  "Created 2019-07-17.")

(custom-theme-set-variables
 'iomonad
 '(custom-safe-themes (quote ("59e82a683db7129c0142b4b5a35dbbeaf8e01a4b81588f8c163bd255b76f4d21" default)))
 '(package-selected-packages (quote (cyberpunk-2019-theme intero yasnippet-snippets use-package undo-tree twilight-theme tuareg request multiple-cursors markdown-mode magit go-mode go-autocomplete ensime distinguished-theme cyberpunk-theme cider)))
 '(large-file-warning-threshold nil))

(custom-theme-set-faces
 'iomonad
 '(mode-line-inactive ((t (:foreground "#CBECFF" :background "#3D5666"))))
 '(cursor ((t (:background "#BEFF00"))))
 '(region ((t (:background "#009fff"))))
 '(bold ((t (:weight normal :foreground "#FF9C00"))))
 '(fringe ((t (:background "#4B3E72"))))
 '(mode-line ((t (:foreground "#FFFAFA" :background "#FF9C00"))))
 '(highlight ((t (:background "#262F36"))))
 '(ido-first-match ((t (:foreground "#D7F0FF" :weight bold))))
 '(ido-only-match ((t (:foreground "#31C0C0"))))
 '(ido-subdir ((t (:foreground "#5DC4FF"))))
 '(isearch ((t (:background "#4D4FBB" :foreground "#FFFAFA"))))
 '(lazy-highlight ((t (:background "#659F93" :foreground "#FFFAFA"))))
 '(linum ((t (:background "#4B3E72" :foreground "#CBEBFF"))))
 '(font-lock-builtin-face ((t (:foreground "#00FFC1"))))
 '(font-lock-doc-face ((t (:foreground "#7FDEFF" :italic t))))
 '(font-lock-comment-face ((t (:foreground "#CBEBFF" :background nil :italic t))))
 '(font-lock-string-face ((t (:foreground "#7FDEFF"))))
 '(font-lock-variable-name-face ((t (:foreground "#FF4081"))))
 '(font-lock-function-name-face ((t (:foreground "#00FF9C"))))
 '(font-lock-keyword-face ((t (:foreground "#00BEFF"))))
 '(font-lock-negation-char-face ((t (:foreground "#5EC4FF"))))
 '(font-lock-preprocessor-face ((t (:foreground "#5EC4FF"))))
 '(font-lock-type-face ((t (:foreground "#FF9C00"))))
 '(font-lock-constant-face ((t (:foreground "#66FFC4"))))
 '(minibuffer-prompt ((t (:foreground "#729FCF"))))
 '(font-lock-warning-face ((t (:foreground "red" :bold t))))
 '(org-block ((t (:background "#4B3E72" :foreground "#00E3FF"))))
 '(org-document-title ((t (:height 2.0 :foreground "#CBEBFF" :family "Georgia"))))
 '(org-level-1 ((t (:inherit outline-1 :weight bold :foreground "#7FDEFF" :height 1.3))))
 '(org-level-2 ((t (:inherit outline-2 :weight bold :foreground "#00FFC1" :height 1.1))))
 '(org-level-3 ((t (:inherit outline-3 :weight bold :foreground "#00BEFF" :height 1.1))))
 '(org-table ((t (:background "#FF4081" :foreground "#729FCF"))))
 '(default ((t (:background "#372963" :foreground "#00E3FF")))))

(provide-theme 'iomonad)
