#!/bin/bash
# Update system configurations
# Clement Trosa <me@trosa.io>
#

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

WDIR=`pwd`
PPATH=/etc/portage
PDIR=$WDIR/portage
BDIR=/boot

_retrieve_portage() {
    rm -r $PDIR
    cp -r $PPATH $PDIR
    echo -e 'Done portage.'
}

_retrieve_kernel() {
    cp -r $BDIR/config-* $WDIR/kernel
    cp -r /usr/src/linux/.config $WDIR/kernel/mainline-config
    echo -e 'Done kernel configs.'
}

_retrieve_grub() {
    cp -r --no-preserve=mode,ownership $BDIR/grub/grub* $WDIR/grub    
    echo -e 'Done grub configs.'
}

_retrieve_sysctl() {
    cp -r /etc/sysctl.conf $WDIR/sysctl    
    echo -e 'Done sysctl config.'
}

_retrieve_rc() {
    cp -r /etc/rc.conf $WDIR/rc
    rm -r $WDIR/rc/conf.d
    cp -r /etc/conf.d $WDIR/rc
    echo -e 'Done sysctl config.'
}

main () {
    _retrieve_portage
    _retrieve_kernel
    _retrieve_grub
    _retrieve_sysctl
    _retrieve_rc
}

sandbox
sudo ./$0
exit 0
