" File: .vimrc
" Author: Clement Trosa <me@trosa.io>
" Date: 18/06/2017 06:56:54 PM
" Last Modified: 28/06/2017 11:18:45 AM

set nocompatible " Remove vi features

let loadpath = ["custom", "languages", "mail"]

" Load file in path
for p in loadpath
  for f in split(globpath(globpath('~/.vim/', p), "*.vim"), '\n')
    exe 'source' f
  endfor
endfor
