#!/bin/bash

sxhkd &
bspc monitor -d "i" "ii" "iii" "iv" "v" "vi"

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

desktop_config() {
    bspc config $1 $2
    for M in $(bspc query -M); do
        bspc config -m $M $1 $2
    done
}

desktop_config border_width 0
desktop_config window_gap 24

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#cccccc"
bspc config focused_border_color "#333333"
bspc config presel_border_color "#cc6666"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.0


# Rules
bspc rule -a gimp floating=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Thunar pseudo_tiled=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a feh floating=on manage=off

# Exec on start
wmname LG3D
compton --config $HOME/etc/compton/smooth.conf &
statusbar
