#! /bin/sh
sxhkd &
compton --config ~/.config/ccandy.conf &

bspc config border_width        5
bspc config window_gap          0
bspc config top_padding         0
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0


bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled   true


bspc config normal_border_color "#131313"
bspc config focused_border_color "#683e3e"
bspc config presel_feedback_color "#51c4d4"


bspc monitor -d I II III IV V

bspc rule -a java  state=float
bspc rule -a feh state=full
bspc rule -a mplayer state=full
bspc rule -a URxvt:mutt desktop=^3 follow=on
bspc rule -a URxvt:weechat desktop=^1 follow=on
bspc rule -a qtox desktop=^4 follow=on state=float

