#! /bin/sh

sxhkd &
compton &
bspc config border_width        5
#bspc config window_gap          30
bspc config window_gap          3
bspc config top_padding         3
bspc config left_padding        3
bspc config right_padding       3
bspc config bottom_padding      3


bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_by_distance    	true
bspc config history_aware_focus  	true
bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	false
bspc config click_to_focus 			false
bspc config adaptive raise 			true

bspc config center_pseudo_tiled  true


bspc config normal_border_color   #151515 #$(xrq color8)
bspc config focused_border_color  #3D3D3D $(xrq color0)
bspc config presel_feedback_color $(xrq color1)


bspc monitor -d i ii iii iv v

bspc rule -a firefox desktop=^2 follow=on state=fullscreen
bspc rule -a URxvt:updates state=floating
bspc rule -a URxvt:pulsemixer state=floating
bspc rule -a URxvt:mutt desktop=^2 follow=on
bspc rule -a URxvt:weechat desktop=^2 follow=on
bspc rule -a Gimp desktop=^4 follow=on
bspc rule -a URxvt:vpn desktop=^5 follow=on state=floating
bspc rule -a URxvt:upass state=floating

