# Load X ressources
xrdb -load  $HOME/.Xresources
xset +fp ~/.fonts
xset fp rehash
xset -dpms
xrdb -load .Xresources
xsetroot -cursor_name left_ptr &
wmname LG3D
unclutter&
urxvtd --quiet --opendisplay --fork
autocutsel -selection clipboard -fork
hsetroot -tile .wall.png
compton -c -t-5 -l-5 -r3 -o.48 &
#exec redhsift -l 48.886764:2.320873 # long / lat
#exec xmonad
#exec ~/documents/sources/stumpwm/stumpwm
exec i3
xset r rate 220 60
