# Load X ressources
xrdb -load  $HOME/.Xresources
xset +fp ~/.fonts
xset fp rehash
xset -dpms
xrdb -load .Xresources
xsetroot -cursor_name left_ptr &
wmname LG3D
urxvtd --quiet --opendisplay --fork
autocutsel -selection clipboard -fork
rm ~/.serverauth*
hsetroot -tile $HOME/.xres.d/wallpaper/chicago1.jpg
exec xmonad