{:user {:plugins [[jonase/eastwood "0.9.9"]
                  [lein-ancient "1.0.0-RC3"]
                  [lein-marginalia "0.9.1"]
                  [io.aviso/pretty "1.1.1"]
                  [lein-cljfmt "0.8.0"]
		  [lein-cloverage "1.2.2"]
                  [venantius/yagni "0.1.7"]
                  [lein-marginalia "0.9.1"]
                  [nvd-clojure "3.2.0"]]
        :dependencies [[io.aviso/pretty "1.1.1"]]
        :middleware [io.aviso.lein-pretty/inject]}}
