#!/bin/bash
#
# (c) 2018 iomonad - <me@trosa.io>
#
# ncmpcpp notifier using beet's
# covers image files.
#

#
# Options
#

shopt -s extglob
shopt -s nocaseglob

#
# Globals
#

MPD_PATH=$HOME/medias/musique
LOCAL_ART=$(dirname "$(mpc status -f '%file%' | head -n1)")
ARTS=($MPD_PATH/$LOCAL_ART/*.{jpg,jgeg,png})
ART="$MPD_PATH/$LOCAL_ART/cover.jpg"
CURRENT=$(mpc current)
CACHE_DIR=$HOME/.cache/covers
TARGET=

#
# Functions
#

function prepare () {
	mkdir -p $CACHE_DIR

	# for i in "${ARTS[@]}"; do
	# 	echo -e "$i"
	# done

	if [ -e "$ART" ]
	then
		HASH=$(md5sum "$ART" | awk '{print $1}')
		if [ ! -e "$CACHE_DIR/$HASH.png" ]; then
			convert -resize 128x128 "$ART" $CACHE_DIR/$HASH.png >/dev/null 2>&1
		fi
		TARGET=$CACHE_DIR/$HASH.png
	else
		TARGET=$HOME/.mpd/generic.png
	fi
}

function main () {
	notify-send -u low "Mpd" "$CURRENT" -i "${TARGET}"
}

function cleanup () {
	exit 0
}

#
# Entrypoints
#

prepare
main
cleanup
