#!/bin/sh
repository_name=${1}
# The URI to which the repository was synced.
sync_uri=${2}
# The path to the repository.
repository_path=${3}

# Portage assumes that a hook succeeded if it exits with 0 code. If no
# explicit exit is done, the exit code is the exit code of last spawned
# command. Since our script is a bit more complex, we want to control
# the exit code explicitly.
ret=0

if [ -n "${repository_name}" ]; then
	# Repository name was provided, so we're in a post-repository hook.
	echo "* In post-repository hook for ${repository_name}"
	echo "** synced from remote repository ${sync_uri}"
	echo "** synced into ${repository_path}"

	# Gentoo comes with pregenerated cache but the other repositories
	# usually don't. Generate them to improve performance.
	if [ "${repository_name}" != "gentoo" ]; then
		if ! egencache --update --repo="${repository_name}" --jobs=4
		then
			echo "!!! egencache failed!"
			ret=1
		fi
	fi
fi

# Return explicit status.
exit "${ret}"
