## {{{ ZSH main config file
##

## Source other config files
for r in $HOME/.config/zsh/*.zsh; do
  if [[ $DEBUG > 0 ]]; then
    echo "zsh: sourcing $r"
  fi
  source $r
done

# {{{ if ... else ... fi
# root & user
if [ $UID -eq 0 ]; then 
    CARETCOLOR="red"
    # user_prompt="⚡"
    # user_prompt="#"
else 
    CARETCOLOR="green"
    # user_prompt="»"
fi

export HISTFILE=~/.config/zsh/zsh-history
export HISTSIZE=10000
export SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_SAVE_NO_DUPS
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY

#Don't share history between terminals
unsetopt APPEND_HISTORY
stty -ixon

xrdb .Xresources

if pgrep -x "gpg-agent" > /dev/null
then
    true
else
    gpg-agent --daemon
fi
        
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec startx; fi
export TERM=rxvt
