#!/bin/zsh
# (c) 2015 iomonad <iomonad@riseup.net>
#

COMPILE=false

for r in $HOME/.zsh/*.zsh; do
    if [[ ${+DEBUG} > 0 ]]; then
	echo "ZSH: Sourcing $r"
    fi
    if $COMPILE = true ; then
        builtin zcompile -ca -M $r
    else
	builtin source $r
    fi
done

for r in $HOME/.zsh/vendor/*.zsh; do
    if [[ ${+DEBUG} > 0 ]]; then
	echo "ZSH: Vendors Sourcing $r"
    fi
    if $COMPILE = true ; then
        builtin zcompile -ca -M $r
    else
	builtin source $r
    fi
done
